
[splunktcp://9997]
disabled = 0
[monitor:///var/log/nginx/access_real.log]
sourcetype = nginx:access
index = main
disabled = false

[monitor:///var/log/nginx/error.log]
sourcetype = nginx:error
index = main
disabled = false

[monitor:///var/lib/docker/containers]
sourcetype = docker:json
index = main
disabled = false
recursive = true
