
[httpServer]
mgmtMode = auto

[sslConfig]
sslPassword = $7$2ovQhKyS52fleOPi1jUKZigSGNklXkLh/+t+t0N2T7CnpUbfAE2Xcg==

[general]
pass4SymmKey = $7$ZnGPt5wSvi1WCChK+8c9ACjM5PRK2WGg5aO9kmCKbmW42DWBnlBqLA==

[lmpool:auto_generated_pool_forwarder]
description = auto_generated_pool_forwarder
peers = *
quota = MAX
stack_id = forwarder

[lmpool:auto_generated_pool_free]
description = auto_generated_pool_free
peers = *
quota = MAX
stack_id = free
